import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'


export const metadata = {
  title: 'Workzone',
  description: 'Generated by CWR',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className='bg-[#F5F6F8]'>{children}</body>
      </html>
    </ClerkProvider>
  )
}
